#Will run unittests

name: Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install from conda enviroment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        conda env create --name FRAME_LINUX --file=environment_linux.yml
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate FRAME_LINUX
        conda info
        python UnitTests/test_fgmap.py